### ISSUE TITLE
There is no support for booleans

### ISSUE THREAD

**Issue by Jex-y** [TorinFelton/NEA_ProgrammingLanguage#3]
I mean I could use strings for Booleans but that would be a stupid idea and is incredibly memory inefficent.

**Comment by TorinFelton** [comment]
This is out of the NEA scope but will likely be added to the experimental branch soon.

**Comment by TorinFelton** [comment]
Added booleans to [experimental branch](https://github.com/TorinFelton/NEA_ProgrammingLanguage/tree/experimental).
